# function to handle errors with inputs 
def try_except_execute(func, lst, page):

    '''
    Function to handle input errors

    func -> function named which is used to perform task
    lst -> list of valid values which can be taken from input
    page -> setting correct page according to output generated by user input
    
    '''

    # default variable for if loop is being breaked or continued and if logged in or not
    break_or_continue = ''
    logged_in = False

    # error handling block start
    try:
        # user input caste to integer
        res = int(input('$ '))

    except:  # if error is raised

        print('You raised an error! I couldn\'t process that input. Try Again\n')
        break_or_continue = 'continue'
        
    else: # if error not raised


        if res in lst:  # Valid Input passed then break loop

            # control flow for homepage text
            page, logged_in = func(res, page)
            break_or_continue = 'break'
        
        else:  # valid input is not passed then continue loop

            print('Your number didn\'t match with valid inputs. Try Again\n')
            break_or_continue = 'continue'

    # returning necessary values
    return break_or_continue, page, logged_in